name: Build
run-name: ${{ github.actor }} running Build
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install Dependencies
      run: ./deploy/install_dependencies_ubuntu.sh
      shell: bash
    - name: Build
      run: ./deploy/build.sh
      shell: bash