name: Build
run-name: ${{ github.actor }} running Build
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main, develop ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install Dependencies
      run: ./deploy/dependencies/install_dependencies_ubuntu.sh
      shell: bash
    - name: Build
      run: ./deploy/build.sh
      shell: bash
    - name: Install
      run: ./deploy/install.sh
      shell: bash
  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - name: Install Development Dependencies
        run: ./deploy/dependencies/install_development_dependencies.sh
        shell: bash
      - name: Lint with Linux checkpath
        run: ./tests/test_checkpath.sh
        shell: bash
      - name: Lint with pylint
        run: ./tests/test_python.sh
        shell: bash
      - name: Test python CLI
        run: ./tests/test_python_cli.sh
        shell: bash
      - name: Test python GUI
        run: ./tests/test_python_gui.sh
        shell: bash